### ISSUE TITLE
undefined parse transform 'bhvs2_pt'

### ISSUE THREAD

**Issue by Zabrane** [efcasado/behaviours2#1]
@efcasado would it possible to update `behaviours2` to make it work with recent Erlang releases (24+25) and rebar3?

As you can see, it fails to compile even the default example:
```erlang
-module(db_user).
-compile({parse_transform, bhvs2_pt}).
-behaviour(my_awesome_behaviour).

f2() ->
  'custom_f2'.
```

```
===> Compiling apps/src/db_user.erl failed
apps/minex_user/src/db_user.erl:none: error in parse transform 'bhv2_pt':
exception error: undefined function meta:behaviours/1
  in function  bhv2_pt:parse_transform/2 (_build/default/lib/behaviours2/src/bhv2_pt.erl, line 47)
  in call from compile:foldl_transform/3 (compile.erl, line 1147)
  in call from compile:fold_comp/4 (compile.erl, line 418)
  in call from compile:internal_comp/5 (compile.erl, line 402)
  in call from compile:'-internal_fun/2-anonymous-0-'/2 (compile.erl, line 229)
/src/rebar_compiler_erl.erl, line 157)
/src/rebar_compiler.erl, line 329)
```

I'm using rebar `3.19.0` and `Erlang/OTP 24` (Erts 12.3.1). The same issue happens with `Erlang 25`.
Many thanks

**Comment by efcasado** [comment]
Sure thing!

I haven't worked on the project for a long time, but I could give it a try this weekend.

By the way, I'm really sorry it took me this long to get back to you. I haven't been paying much attention to my GitHub feed 😅

**Comment by Zabrane** [comment]
@efcasado I was almost desperate but I'm glad you can resurrect this beautiful piece of code ;-)
Please let me know when i can try again.

**Comment by efcasado** [comment]
@Zabrane I believe it should be fixed now. See [this](https://github.com/efcasado/behaviours2/pull/2) `PR`. The change is included in `0.0.1`. If it doesn't work, could you share a complete example that illustrates how you are using it so that I can debug the issue further? :)

**Comment by Zabrane** [comment]
@efcasado sorry for being late to answer because i didn't get notification from GitHub.
I will test it and report back ;-)
Happy New Year.

**Comment by Zabrane** [comment]
@efcasado testing with Erlang (24 & 25) on `MacOS`, i still get a compile error with this example:
```erlang
-module(echo_server).
-compile({parse_transform, bhv2_pt}).

-behaviour(gen_server).

-export([handle_call/3]).

handle_call(Msg, From, State) ->
  Reply = Msg,
  {reply, Msg, State}.
```

Then, run:
```bash
$ rebar3 compile
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling bhv2
===> Compiling src/echo_server.erl failed
src/echo_server.erl:none: error in parse transform 'bhv2_pt':
exception error: no function clause matching bhv2_pt:'_filter_out_duplicates'([undefined],
 [{attribute,{45,2},record,{state,[]}},
  {attribute,
      {58,2},
      spec,
      {{init,1},
       [{type,
            {58,11},
            'fun',
            [{type,
                 {58,11},
                 product,
                 [{ann_type,
                      {58,12},
                      [{var,{58,12},'Args'},{type,{58,20},nil,[]}]}]},
             {type,
                 {59,11},
                 union,
                 [{type,
                      {59,11},
                      tuple,
                      [{atom,{59,12},ok},{user_type,{59,18},state,[]}]},
                  {type,
                      {60,11},
                      tuple,
                      [{atom,{60,12},ok},
                       {user_type,{60,18},state,[]},
                       {type,{60,27},timeout,[]}]},
                  {atom,{61,11},ignore},
                  {type,
                      {62,11},
                      tuple,
                      [{atom,{62,12},stop},
                       {ann_type,
                           {62,20},
                           [{var,{62,20},'Reason'},
                            {type,{62,30},term,[]}]}]}]}]}]}},
  {function,
      {63,1},
      init,1,
      [{clause,
           {63,1},
           [{nil,{63,6}}],
           [],
           [{tuple,{64,5},[{atom,{64,6},ok},{record,{64,10},state,[]}]}]}]}],
 [{attribute,
      {1,1},
      file,
      {"/Users/zab/Documents/wab/behaviours2/src/echo_server.erl",1}},
  {attribute,{1,2},module,echo_server},
  {attribute,{5,2},behaviour,gen_server},
  {attribute,
      {7,2},
      export,
      [{handle_call,3},
       {init,1},
       {handle_cast,2},
       {handle_info,2},
       {handle_continue,2},
       {terminate,2},
       {code_change,3},
       {format_status,2},
       {format_status,1}]},
  {function,
      {9,1},
      handle_call,3,
      [{clause,
           {9,1},
           [{var,{9,13},'Msg'},{var,{9,18},'From'},{var,{9,24},'State'}],
           [],
           [{match,{10,3},{var,{10,3},'Reply'},{var,{10,11},'Msg'}},
            {tuple,
                {11,3},
                [{atom,{11,4},reply},
                 {var,{11,11},'Msg'},
                 {var,{11,16},'State'}]}]}]},
  {eof,{12,1}}]) (/Users/zab/Documents/wab/behaviours2/src/bhv2_pt.erl, line 134)
  in function  bhv2_pt:inject_defaults/2 (/Users/zab/Documents/wab/behaviours2/src/bhv2_pt.erl, line 120)
  in call from compile:foldl_transform/3 (compile.erl, line 1172)
  in call from compile:fold_comp/4 (compile.erl, line 405)
  in call from compile:internal_comp/5 (compile.erl, line 389)
  in call from compile:'-internal_fun/2-anonymous-0-'/2 (compile.erl, line 227)
  in call from rebar_compiler_erl:compile_and_track/4 (/Users/zab/Desktop/rebar3/src/rebar_compiler_erl.erl, line 157)
  in call from rebar_compiler:compile_worker/2 (/Users/zab/Desktop/rebar3/src/rebar_compiler.erl, line 329)
```
